import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import SearchBox from "../components/SearchBox";
import styles from "../styles/Home.module.css";
import SearchIcon from "../public/icons/search.svg";
import { Dialog } from "@headlessui/react";

const Home: NextPage = () => {
  let [isOpen, setIsOpen] = useState(false);

  const openSearch = () => {
    setIsOpen(true);
  };
  const closeSearch = () => {
    setIsOpen(false);
  };
  return (
    <div className={`overflow-hidden bg-slate-900  w-full min-h-[100vh]`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* search overlay */}
      <Dialog
        open={isOpen}
        onClose={closeSearch}
        className="fixed inset-0 overflow-y-auto "
      >
        <div className="flex items-center justify-center min-h-screen">
          <Dialog.Overlay className="absolute inset-0 bg-slate-900/80 backdrop-blur-sm" />

          <div className="relative w-full">
            <SearchBox onInput={() => {}} />
          </div>
        </div>
      </Dialog>

      <main className="relative flex flex-col items-center justify-center gap-8 py-6 px-10">
        <div className="form-input">
          <label htmlFor="username"></label>
          <button
            className="flex gap-2 text-[Inter] text-sm tracking-wide text-gray-300 border-gray-800  bg-gray-800 hover:bg-gray-700 w-60 items-center rounded-md py-1.5 pl-2 pr-3 shadow-sm ring-2 ring-slate-500 hover:ring-sky-500 highlight-white-5 focus:outline-none"
            onClick={openSearch}
            // onKeyPress={openSearch}
          >
            <span>
              <SearchIcon />
            </span>
            Search Username
          </button>
        </div>
        <div className="w-[400px] h-[500px] bg-blur"></div>
      </main>
    </div>
  );
};

export default Home;
